import { NextResponse } from "next/server";
import { createEvent } from "ics";

import { dbConnect } from "@/lib/db";
import { requireUserId } from "@/lib/guards";
import { Profile } from "@/models/Profile";
import { Period } from "@/models/Period";
import { computePredictions } from "@/lib/predictions";
import { diffDaysUTC } from "@/lib/dateOnly";

export const runtime = "nodejs";

function dateTupleUTC(d: Date): [number, number, number] {
  return [d.getUTCFullYear(), d.getUTCMonth() + 1, d.getUTCDate()];
}

export async function GET() {
  const userId = await requireUserId();
  await dbConnect();

  const profile = await Profile.findOne({ userId }).lean();
  if (!profile?.onboardingCompleted) {
    return NextResponse.json(
      { error: "Complete onboarding before exporting calendar events." },
      { status: 400 }
    );
  }

  const periods = await Period.find({ userId })
    .sort({ startDate: -1 })
    .limit(24)
    .lean();

  const predictions = computePredictions(periods, {
    cycleLengthTypical: profile.cycleLengthTypical ?? 28,
    periodLengthTypical: profile.periodLengthTypical ?? 5,
  });

  if (!predictions.fertileWindowStart || !predictions.fertileWindowEnd) {
    return NextResponse.json(
      { error: "Not enough history to generate a fertile-window event." },
      { status: 400 }
    );
  }

  const durationDays =
    diffDaysUTC(predictions.fertileWindowEnd, predictions.fertileWindowStart) + 1;

  const { error, value } = createEvent({
    title: "Fertile window (estimate)",
    description:
      "Estimates only. Not medical advice and not birth control. This event was generated by Period Tracker.",
    start: dateTupleUTC(predictions.fertileWindowStart),
    duration: { days: durationDays },
    startInputType: "utc",
  });

  if (error || !value) {
    return NextResponse.json(
      { error: "Failed to generate calendar event." },
      { status: 500 }
    );
  }

  return new NextResponse(value, {
    status: 200,
    headers: {
      "Content-Type": "text/calendar; charset=utf-8",
      "Content-Disposition": 'attachment; filename="fertile-window.ics"',
      "Cache-Control": "no-store",
    },
  });
}

